### ISSUE TITLE
Let's build polysemy with latest stackage and ghc 8.8

### ISSUE THREAD

**Issue by googleson78** [polysemy-research/polysemy#235]
Not sure if I'm acting out of place or there are some other considerations which I'm missing (in which cases, sorry and feel free to close!) but it would be nice to have `polysemy` in an lts/nightly with ghc 8.8.

I tried to build `polysemy` with `nightly-2019-09-30` and found the following things to do:

* [x] get `loopbreaker` to work with ghc 8.8 - https://github.com/polysemy-research/loopbreaker/issues/6
* [x] depend on `first-class-families` `0.6.0.0`
We can either bump the version in `polysemy`'s `stack.yaml`, or we can depend on the nightly stackage's `first-class-families` (which coincidentally is exactly `0.6.0.0` in `nightly-2019-09-30`.
* [x] depend on a version `>=  0.0.1.0` of `type-errors-pretty`, because it has a `base` restriction before that
It hasn't been uploaded to Hackage yet, however. https://github.com/chshersh/type-errors-pretty/issues/6
* [x] depend on a later `unagi-chan` - `0.4.1.0` has an upper bound on `primitive`, which is later removed
a `base` restriction of `< 4.13` is however added in [Revision 1](https://hackage.haskell.org/package/unagi-chan-0.4.1.2/revisions/) - I don't really understand this, but we can either depend on `0.4.1.2:rev0`, which doesn't have the restriction, or wait for the situation there to be resolved (?)

**Comment by TheMatten** [comment]
@isovector Do we just want to jump on current (at the moment nightly) snapshots from now on, or wait for LTS? Or create separate configuration?

**Comment by Tehnix** [comment]
Don't know if this is helpful at all, but it seems both `unagi-chan` and `type-errors-pretty` are working if you use them from GitHub HEAD.

The following stack.yaml currently works for me with GHC 8.8.1:

```
resolver: nightly-2019-10-14
packages:
- .
extra-deps:
- polysemy-1.2.1.0
- polysemy-plugin-0.2.3.0
- loopbreaker-0.1.1.1
- github: jberryman/unagi-chan
  commit: 671ee5dc4c6894a51bc216bdb18fa21e42e4cdba
- github: chshersh/type-errors-pretty
  commit: 93f7f90c6b956bd5ab59645746c4a78e3f8d1676
```
